package cn.ibilling.bean.dto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductDO implements Serializable {
    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品ID
     * 对应数据库字段 product.PRODUCT_ID
     */
    private String productId;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 计费方式
            后付费
            预付费
            预存款
     * 对应数据库字段 product.BILLING_MODE_ID
     */
    private String billingModeId;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品名称
     * 对应数据库字段 product.PRODUCT_NAME
     */
    private String productName;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品类型
     * 对应数据库字段 product.PRODUCT_TYPE
     */
    private String productType;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.PROPERTY_TYPE
     */
    private String propertyType;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.EFF_DATE
     */
    private Date effDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.EXP_DATE
     */
    private Date expDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品状态
     * 对应数据库字段 product.STATE
     */
    private String state;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.CREATE_DATE
     */
    private Date createDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.LAST_UPDATE_DATE
     */
    private Date lastUpdateDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product.REMARK
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_ID
     *
     * @return the value of product.PRODUCT_ID
     *
     * @mbg.generated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_ID
     *
     * @param productId the value for product.PRODUCT_ID
     *
     * @mbg.generated
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.BILLING_MODE_ID
     *
     * @return the value of product.BILLING_MODE_ID
     *
     * @mbg.generated
     */
    public String getBillingModeId() {
        return billingModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.BILLING_MODE_ID
     *
     * @param billingModeId the value for product.BILLING_MODE_ID
     *
     * @mbg.generated
     */
    public void setBillingModeId(String billingModeId) {
        this.billingModeId = billingModeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_NAME
     *
     * @return the value of product.PRODUCT_NAME
     *
     * @mbg.generated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_NAME
     *
     * @param productName the value for product.PRODUCT_NAME
     *
     * @mbg.generated
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PRODUCT_TYPE
     *
     * @return the value of product.PRODUCT_TYPE
     *
     * @mbg.generated
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PRODUCT_TYPE
     *
     * @param productType the value for product.PRODUCT_TYPE
     *
     * @mbg.generated
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.PROPERTY_TYPE
     *
     * @return the value of product.PROPERTY_TYPE
     *
     * @mbg.generated
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.PROPERTY_TYPE
     *
     * @param propertyType the value for product.PROPERTY_TYPE
     *
     * @mbg.generated
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EFF_DATE
     *
     * @return the value of product.EFF_DATE
     *
     * @mbg.generated
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EFF_DATE
     *
     * @param effDate the value for product.EFF_DATE
     *
     * @mbg.generated
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.EXP_DATE
     *
     * @return the value of product.EXP_DATE
     *
     * @mbg.generated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.EXP_DATE
     *
     * @param expDate the value for product.EXP_DATE
     *
     * @mbg.generated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.STATE
     *
     * @return the value of product.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.STATE
     *
     * @param state the value for product.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.CREATE_DATE
     *
     * @return the value of product.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.CREATE_DATE
     *
     * @param createDate the value for product.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.LAST_UPDATE_DATE
     *
     * @return the value of product.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for product.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.REMARK
     *
     * @return the value of product.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.REMARK
     *
     * @param remark the value for product.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", billingModeId=").append(billingModeId);
        sb.append(", productName=").append(productName);
        sb.append(", productType=").append(productType);
        sb.append(", propertyType=").append(propertyType);
        sb.append(", effDate=").append(effDate);
        sb.append(", expDate=").append(expDate);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductDO other = (ProductDO) that;
        return (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getBillingModeId() == null ? other.getBillingModeId() == null : this.getBillingModeId().equals(other.getBillingModeId()))
            && (this.getProductName() == null ? other.getProductName() == null : this.getProductName().equals(other.getProductName()))
            && (this.getProductType() == null ? other.getProductType() == null : this.getProductType().equals(other.getProductType()))
            && (this.getPropertyType() == null ? other.getPropertyType() == null : this.getPropertyType().equals(other.getPropertyType()))
            && (this.getEffDate() == null ? other.getEffDate() == null : this.getEffDate().equals(other.getEffDate()))
            && (this.getExpDate() == null ? other.getExpDate() == null : this.getExpDate().equals(other.getExpDate()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getLastUpdateDate() == null ? other.getLastUpdateDate() == null : this.getLastUpdateDate().equals(other.getLastUpdateDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getBillingModeId() == null) ? 0 : getBillingModeId().hashCode());
        result = prime * result + ((getProductName() == null) ? 0 : getProductName().hashCode());
        result = prime * result + ((getProductType() == null) ? 0 : getProductType().hashCode());
        result = prime * result + ((getPropertyType() == null) ? 0 : getPropertyType().hashCode());
        result = prime * result + ((getEffDate() == null) ? 0 : getEffDate().hashCode());
        result = prime * result + ((getExpDate() == null) ? 0 : getExpDate().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getLastUpdateDate() == null) ? 0 : getLastUpdateDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}