package cn.ibilling.bean.dto;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_pricing_plan
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductPricingPlanDO implements Serializable {
    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品ID
     * 对应数据库字段 product_pricing_plan.ID
     */
    private String id;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品包ID
     * 对应数据库字段 product_pricing_plan.OFFER_ID
     */
    private String offerId;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_pricing_plan.PRICING_PLAN_ID
     */
    private String pricingPlanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_pricing_plan
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing_plan.ID
     *
     * @return the value of product_pricing_plan.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing_plan.ID
     *
     * @param id the value for product_pricing_plan.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing_plan.OFFER_ID
     *
     * @return the value of product_pricing_plan.OFFER_ID
     *
     * @mbg.generated
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing_plan.OFFER_ID
     *
     * @param offerId the value for product_pricing_plan.OFFER_ID
     *
     * @mbg.generated
     */
    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing_plan.PRICING_PLAN_ID
     *
     * @return the value of product_pricing_plan.PRICING_PLAN_ID
     *
     * @mbg.generated
     */
    public String getPricingPlanId() {
        return pricingPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing_plan.PRICING_PLAN_ID
     *
     * @param pricingPlanId the value for product_pricing_plan.PRICING_PLAN_ID
     *
     * @mbg.generated
     */
    public void setPricingPlanId(String pricingPlanId) {
        this.pricingPlanId = pricingPlanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pricing_plan
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", offerId=").append(offerId);
        sb.append(", pricingPlanId=").append(pricingPlanId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pricing_plan
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductPricingPlanDO other = (ProductPricingPlanDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOfferId() == null ? other.getOfferId() == null : this.getOfferId().equals(other.getOfferId()))
            && (this.getPricingPlanId() == null ? other.getPricingPlanId() == null : this.getPricingPlanId().equals(other.getPricingPlanId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_pricing_plan
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOfferId() == null) ? 0 : getOfferId().hashCode());
        result = prime * result + ((getPricingPlanId() == null) ? 0 : getPricingPlanId().hashCode());
        return result;
    }
}