package cn.ibilling.bean.dto;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table product_offer
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ProductOfferDO implements Serializable {
    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品ID
     * 对应数据库字段 product_offer.OFFER_ID
     */
    private String offerId;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品名称
     * 对应数据库字段 product_offer.OFFER_NAME
     */
    private String offerName;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_offer.EFF_DATE
     */
    private Date effDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_offer.EXP_DATE
     */
    private Date expDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 产品状态
     * 对应数据库字段 product_offer.STATE
     */
    private String state;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_offer.CREATE_DATE
     */
    private Date createDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_offer.LAST_UPDATE_DATE
     */
    private Date lastUpdateDate;

    /**
     *
     * @mbg.generated do_not_delete_during_merge
     * 
     * 对应数据库字段 product_offer.REMARK
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_offer
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.OFFER_ID
     *
     * @return the value of product_offer.OFFER_ID
     *
     * @mbg.generated
     */
    public String getOfferId() {
        return offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.OFFER_ID
     *
     * @param offerId the value for product_offer.OFFER_ID
     *
     * @mbg.generated
     */
    public void setOfferId(String offerId) {
        this.offerId = offerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.OFFER_NAME
     *
     * @return the value of product_offer.OFFER_NAME
     *
     * @mbg.generated
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.OFFER_NAME
     *
     * @param offerName the value for product_offer.OFFER_NAME
     *
     * @mbg.generated
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.EFF_DATE
     *
     * @return the value of product_offer.EFF_DATE
     *
     * @mbg.generated
     */
    public Date getEffDate() {
        return effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.EFF_DATE
     *
     * @param effDate the value for product_offer.EFF_DATE
     *
     * @mbg.generated
     */
    public void setEffDate(Date effDate) {
        this.effDate = effDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.EXP_DATE
     *
     * @return the value of product_offer.EXP_DATE
     *
     * @mbg.generated
     */
    public Date getExpDate() {
        return expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.EXP_DATE
     *
     * @param expDate the value for product_offer.EXP_DATE
     *
     * @mbg.generated
     */
    public void setExpDate(Date expDate) {
        this.expDate = expDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.STATE
     *
     * @return the value of product_offer.STATE
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.STATE
     *
     * @param state the value for product_offer.STATE
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.CREATE_DATE
     *
     * @return the value of product_offer.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.CREATE_DATE
     *
     * @param createDate the value for product_offer.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.LAST_UPDATE_DATE
     *
     * @return the value of product_offer.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for product_offer.LAST_UPDATE_DATE
     *
     * @mbg.generated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_offer.REMARK
     *
     * @return the value of product_offer.REMARK
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_offer.REMARK
     *
     * @param remark the value for product_offer.REMARK
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_offer
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", offerId=").append(offerId);
        sb.append(", offerName=").append(offerName);
        sb.append(", effDate=").append(effDate);
        sb.append(", expDate=").append(expDate);
        sb.append(", state=").append(state);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", remark=").append(remark);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_offer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProductOfferDO other = (ProductOfferDO) that;
        return (this.getOfferId() == null ? other.getOfferId() == null : this.getOfferId().equals(other.getOfferId()))
            && (this.getOfferName() == null ? other.getOfferName() == null : this.getOfferName().equals(other.getOfferName()))
            && (this.getEffDate() == null ? other.getEffDate() == null : this.getEffDate().equals(other.getEffDate()))
            && (this.getExpDate() == null ? other.getExpDate() == null : this.getExpDate().equals(other.getExpDate()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getLastUpdateDate() == null ? other.getLastUpdateDate() == null : this.getLastUpdateDate().equals(other.getLastUpdateDate()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_offer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOfferId() == null) ? 0 : getOfferId().hashCode());
        result = prime * result + ((getOfferName() == null) ? 0 : getOfferName().hashCode());
        result = prime * result + ((getEffDate() == null) ? 0 : getEffDate().hashCode());
        result = prime * result + ((getExpDate() == null) ? 0 : getExpDate().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getLastUpdateDate() == null) ? 0 : getLastUpdateDate().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}